const SampleData = [
  {
    asin: "B08Z265BJH",
    bestseller: {
      category: "LED & LCD TVs",
      link: "https://www.amazon.com/gp/bestsellers/electronics/6459737011/ref=sr_bs_0_6459737011_1",
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/81kRxFTpd1L._AC_UY218_.jpg",
    link: "https://www.amazon.com/Insignia-50-inch-Class-Smart-Fire/dp/B08Z265BJH/ref=sr_1_1?keywords=tv&qid=1659571144&sr=8-1",
    position: 1,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$239.99",
      symbol: "$",
      value: 239.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$239.99",
        symbol: "$",
        value: 239.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$399.99",
        symbol: "$",
        value: 399.99,
      },
    ],
    rating: 4.6,
    ratings_total: 1210,
    title:
      "Insignia 50-inch Class F30 Series LED 4K UHD Smart Fire TV (NS-50F301NA22, 2021 Model)",
  },
  {
    asin: "B08X7K3H7K",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/81DnMWhQ2gL._AC_UY218_.jpg",
    link: "https://www.amazon.com/Insignia-43-inch-Class-Smart-Fire/dp/B08X7K3H7K/ref=sr_1_2?keywords=tv&qid=1659571144&sr=8-2",
    position: 2,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$189.99",
      symbol: "$",
      value: 189.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$189.99",
        symbol: "$",
        value: 189.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$299.99",
        symbol: "$",
        value: 299.99,
      },
    ],
    rating: 4.6,
    ratings_total: 4128,
    title:
      "Insignia 43-inch Class F30 Series LED 4K UHD Smart Fire TV (NS-43F301NA22, 2021 Model)",
  },
  {
    asin: "B08SVZ775L",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Mon, Aug 8",
    },
    image: "https://m.media-amazon.com/images/I/51EPd38RHQL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/amazon-fire-tv-50-inch-4-series-4k-smart-tv/dp/B08SVZ775L/ref=sr_1_3?keywords=tv&qid=1659571144&sr=8-3",
    position: 3,
    price: {
      asin: "B08SVZ775L",
      currency: "USD",
      link: "https://www.amazon.com/amazon-fire-tv-50-inch-4-series-4k-smart-tv/dp/B08SVZ775L/ref=sr_1_3?keywords=tv&qid=1659571144&sr=8-3",
      raw: "$469.99",
      symbol: "$",
      value: 469.99,
    },
    prices: [
      {
        asin: "B08SVZ775L",
        currency: "USD",
        link: "https://www.amazon.com/amazon-fire-tv-50-inch-4-series-4k-smart-tv/dp/B08SVZ775L/ref=sr_1_3?keywords=tv&qid=1659571144&sr=8-3",
        raw: "$469.99",
        symbol: "$",
        value: 469.99,
      },
    ],
    rating: 4.6,
    ratings_total: 16000,
    title: 'Amazon Fire TV 50" 4-Series 4K UHD smart TV',
  },
  {
    asin: "B08T6J1HG8",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
    },
    image: "https://m.media-amazon.com/images/I/51EBhwkD+kL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/amazon-fire-tv-65-inch-omni-series-4k-smart-tv/dp/B08T6J1HG8/ref=sr_1_4?keywords=tv&qid=1659571144&sr=8-4",
    position: 4,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$499.99",
      symbol: "$",
      value: 499.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$499.99",
        symbol: "$",
        value: 499.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$829.99",
        symbol: "$",
        value: 829.99,
      },
    ],
    rating: 4.6,
    ratings_total: 11809,
    title:
      'Amazon Fire TV 65" Omni Series 4K UHD smart TV with Dolby Vision, hands-free with Alexa',
  },
  {
    asin: "B08X7GBPSJ",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/81kQyu0HvbL._AC_UY218_.jpg",
    link: "https://www.amazon.com/All-New-Insignia-NS-42F201NA22-42-inch-Released/dp/B08X7GBPSJ/ref=sr_1_5?keywords=tv&qid=1659571144&sr=8-5",
    position: 5,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$179.99",
      symbol: "$",
      value: 179.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$179.99",
        symbol: "$",
        value: 179.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$269.99",
        symbol: "$",
        value: 269.99,
      },
    ],
    rating: 4.5,
    ratings_total: 2663,
    title:
      "Insignia 42-inch Class F20 Series Smart Full HD 1080p Fire TV (NS-42F201NA22, 2021 Model)",
  },
  {
    asin: "B07FPP6TB5",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/81lj598woRL._AC_UY218_.jpg",
    link: "https://www.amazon.com/Insignia-NS-32DF310NA19-32-inch-720p-Smart/dp/B07FPP6TB5/ref=sr_1_6?keywords=tv&qid=1659571144&sr=8-6",
    position: 6,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$119.99",
      symbol: "$",
      value: 119.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$119.99",
        symbol: "$",
        value: 119.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$179.99",
        symbol: "$",
        value: 179.99,
      },
    ],
    rating: 4.6,
    ratings_total: 79180,
    title:
      "Insignia 32-inch Class F20 Series Smart HD 720p Fire TV (NS-32DF310NA19, 2018 Model)",
  },
  {
    asin: "B08X7JSCHQ",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/61qXHwJeGVS._AC_UY218_.jpg",
    link: "https://www.amazon.com/All-New-Insignia-NS-32F201NA22-32-inch-Released/dp/B08X7JSCHQ/ref=sr_1_7?keywords=tv&qid=1659571144&sr=8-7",
    position: 7,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$119.99",
      symbol: "$",
      value: 119.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$119.99",
        symbol: "$",
        value: 119.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$179.99",
        symbol: "$",
        value: 179.99,
      },
    ],
    rating: 4.5,
    ratings_total: 2280,
    title:
      "Insignia 32-inch Class F20 Series Smart HD 720p Fire TV (NS-32F201NA22, 2021 Model)",
  },
  {
    asin: "B08PDTM9ZD",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Mon, Aug 8",
    },
    image: "https://m.media-amazon.com/images/I/71RshxhlEiL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/Hisense-65-Inch-Vision-Compatibility-65R6G/dp/B08PDTM9ZD/ref=sr_1_8?keywords=tv&qid=1659571144&sr=8-8",
    position: 8,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$409.99",
      symbol: "$",
      value: 409.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$409.99",
        symbol: "$",
        value: 409.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$799.99",
        symbol: "$",
        value: 799.99,
      },
    ],
    rating: 4.5,
    ratings_total: 663,
    title:
      "Hisense 65-Inch Class R6 Series Dolby Vision HDR 4K UHD Roku Smart TV with Alexa Compatibility (65R6G, 2021 Model)",
  },
  {
    asin: "B09R6SNNMG",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Wed, Aug 10",
    },
    image: "https://m.media-amazon.com/images/I/71s3xYeL2jL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/TCL-Class-UHD-Smart-Roku/dp/B09R6SNNMG/ref=sr_1_9?keywords=tv&qid=1659571144&sr=8-9",
    position: 9,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$429.99",
      symbol: "$",
      value: 429.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$429.99",
        symbol: "$",
        value: 429.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$799.99",
        symbol: "$",
        value: 799.99,
      },
    ],
    rating: 4.2,
    ratings_total: 86,
    title: 'TCL 65" Class 4-Series 4K UHD HDR Smart Roku TV – 65S455',
  },
  {
    asin: "B088S3V3R4",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Mon, Aug 8",
    },
    image: "https://m.media-amazon.com/images/I/61--xSgNcQL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/TCL-32-720p-ROKU-Smart/dp/B088S3V3R4/ref=sr_1_10?keywords=tv&qid=1659571144&sr=8-10",
    position: 10,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$149.99",
      symbol: "$",
      value: 149.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$149.99",
        symbol: "$",
        value: 149.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$229.99",
        symbol: "$",
        value: 229.99,
      },
    ],
    rating: 4.6,
    ratings_total: 13017,
    title: "TCL 32-inch 3-Series 720p Roku Smart TV - 32S335, 2021 Model",
  },
  {
    asin: "B09WQDRL83",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
    },
    image: "https://m.media-amazon.com/images/I/81MclOJOe7L._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/Hisense-75-Inch-Virtual-Chromecast-75A6H/dp/B09WQDRL83/ref=sr_1_11?keywords=tv&qid=1659571144&sr=8-11",
    position: 11,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Save 13%",
      raw: "$618.00",
      symbol: "$",
      value: 618,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Save 13%",
        raw: "$618.00",
        symbol: "$",
        value: 618,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Save 13%",
        raw: "$709.99",
        symbol: "$",
        value: 709.99,
      },
    ],
    rating: 4.4,
    ratings_total: 266,
    title:
      "Hisense A6 Series 75-Inch 4K UHD Smart Google TV with Voice Remote, Dolby Vision HDR, DTS Virtual X, Sports & Game Modes, Chromecast Built-in (75A6H, 2022 New Model)",
  },
  {
    asin: "B09R96FLVP",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
    },
    image: "https://m.media-amazon.com/images/I/81-BV4jCJQL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/Sony-Inch-Ultra-X90K-Playstation%C2%AE/dp/B09R96FLVP/ref=sr_1_12?keywords=tv&qid=1659571144&sr=8-12",
    position: 12,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$2,598.00",
      symbol: "$",
      value: 2598,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$2,598.00",
        symbol: "$",
        value: 2598,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$2,999.99",
        symbol: "$",
        value: 2999.99,
      },
    ],
    rating: 4,
    ratings_total: 29,
    title:
      "Sony 85 Inch 4K Ultra HD TV X90K Series: BRAVIA XR Full Array LED Smart Google TV with Dolby Vision HDR and Exclusive Features for The Playstation® 5 XR85X90K- 2022 Model",
  },
  {
    asin: "B07GB61TQR",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Tue, Aug 9",
    },
    image: "https://m.media-amazon.com/images/I/71MVe3Ym8yL._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/TCL-40S325-Inch-1080p-Smart/dp/B07GB61TQR/ref=sr_1_13?keywords=tv&qid=1659571144&sr=8-13",
    position: 13,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$199.99",
      symbol: "$",
      value: 199.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$199.99",
        symbol: "$",
        value: 199.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$349.99",
        symbol: "$",
        value: 349.99,
      },
    ],
    rating: 4.6,
    ratings_total: 38793,
    title: "TCL 40-inch 1080p Smart LED Roku TV - 40S325, 2019 Model , Black",
  },
  {
    asin: "B099XC3GPC",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/91XcODg2NuL._AC_UY218_.jpg",
    link: "https://www.amazon.com/Toshiba-32-inch-HD-v35-Fire-TV-2021/dp/B099XC3GPC/ref=sr_1_14?keywords=tv&qid=1659571144&sr=8-14",
    position: 14,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Limited time deal",
      raw: "$129.99",
      symbol: "$",
      value: 129.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Limited time deal",
        raw: "$129.99",
        symbol: "$",
        value: 129.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Limited time deal",
        raw: "$199.99",
        symbol: "$",
        value: 199.99,
      },
    ],
    rating: 4.5,
    ratings_total: 1289,
    title:
      "Toshiba 32-inch Class V35 Series LED HD Smart Fire TV (32V35KU, 2021 Model)",
  },
  {
    asin: "B09WNJT9X3",
    availability: {
      raw: "Only 4 left in stock - order soon.",
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it Mon, Aug 8 - Thu, Aug 11",
    },
    image: "https://m.media-amazon.com/images/I/61hbJmB1IxL._AC_UY218_.jpg",
    link: "https://www.amazon.com/Hisense-50-inch-Quantum-Smart-50U6HF/dp/B09WNJT9X3/ref=sr_1_15?keywords=tv&qid=1659571144&sr=8-15",
    position: 15,
    price: {
      currency: "USD",
      is_primary: true,
      name: "Primary",
      raw: "$374.95",
      symbol: "$",
      value: 374.95,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "Primary",
        raw: "$374.95",
        symbol: "$",
        value: 374.95,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "Original",
        raw: "$529.99",
        symbol: "$",
        value: 529.99,
      },
    ],
    rating: 4.2,
    ratings_total: 126,
    title:
      "Hisense 50-inch ULED U6 Series Quantum Dot QLED 4K UHD Smart Fire TV (50U6HF, 2022 Model)",
  },
  {
    asin: "B09RRMBP4C",
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    delivery: {
      price: {
        currency: "USD",
        is_free: true,
        raw: "FREE Shipping by Amazon",
        symbol: "$",
        value: 0,
      },
      tagline: "Get it as soon as Mon, Aug 8",
    },
    image: "https://m.media-amazon.com/images/I/A1j2aOql-8L._AC_UY218_.jpg",
    is_prime: true,
    link: "https://www.amazon.com/LG-65-Inch-Refresh-AI-Powered-65UQ9000PUD/dp/B09RRMBP4C/ref=sr_1_16?keywords=tv&qid=1659571144&sr=8-16",
    position: 16,
    price: {
      asin: "B09RRMBP4C",
      currency: "USD",
      link: "https://www.amazon.com/LG-65-Inch-Refresh-AI-Powered-65UQ9000PUD/dp/B09RRMBP4C/ref=sr_1_16?keywords=tv&qid=1659571144&sr=8-16",
      raw: "$626.99",
      symbol: "$",
      value: 626.99,
    },
    prices: [
      {
        asin: "B09RRMBP4C",
        currency: "USD",
        link: "https://www.amazon.com/LG-65-Inch-Refresh-AI-Powered-65UQ9000PUD/dp/B09RRMBP4C/ref=sr_1_16?keywords=tv&qid=1659571144&sr=8-16",
        raw: "$626.99",
        symbol: "$",
        value: 626.99,
      },
    ],
    rating: 4.3,
    ratings_total: 147,
    title:
      "LG 65-Inch Class UQ9000 Series Alexa Built-in 4K Smart TV (3840 x 2160), 60Hz Refresh Rate, AI-Powered 4K, Cloud Gaming (65UQ9000PUD, 2022)",
  },
  {
    asin: "B07FPP6TB5",
    carousel: {
      id: "loom-desktop-bottom-slot_sptw-deals-blended-na-desktop-T4",
      title: "Today's deals",
      total_items: 5,
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    image: "https://m.media-amazon.com/images/I/81lj598woRL._AC_UL320_.jpg",
    is_carousel: true,
    link: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_search_thematic_btf_aps_sr_pg1_1?ie=UTF8&bwType=search&bwAsin=B07FPP6TB5&url=%2FInsignia-NS-32DF310NA19-32-inch-720p-Smart%2Fdp%2FB07FPP6TB5%2Fref%3Dsxbs_pa_sp_search_thematic_btf_sspa%3Fcontent-id%3Damzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%253Aamzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%26cv_ct_cx%3Dtv%26keywords%3Dtv%26pd_rd_i%3DB07FPP6TB5%26pd_rd_r%3D05dd59e4-8cae-48ac-b8c0-f38bdeb61b44%26pd_rd_w%3DvlVGw%26pd_rd_wg%3D8M4SW%26pf_rd_p%3Ddfb5d868-54e5-4c02-b76d-0b517246ef24%26pf_rd_r%3DK94SPT2DX03FY395YTR8%26qid%3D1659571144%26sr%3D1-1-97bafd84-a21b-4eac-aafb-f1e805a45134-spons%26psc%3D1&qualifier=1659571144&id=1920463823263837&widgetName=sp_search_thematic_btf",
    position: 17,
    price: {
      currency: "USD",
      is_primary: true,
      name: "$119.99",
      raw: "$119.99",
      symbol: "$",
      value: 119.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "$119.99",
        raw: "$119.99",
        symbol: "$",
        value: 119.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "$119.99",
        raw: "$179.99",
        symbol: "$",
        value: 179.99,
      },
    ],
    rating: 4.6,
    ratings_total: 79180,
    title:
      "Insignia 32-inch Class F20 Series Smart HD 720p Fire TV (NS-32DF310NA19, 2018 Model)",
  },
  {
    asin: "B08Z265BJH",
    bestseller: {
      category: "LED & LCD TVs",
      link: "https://www.amazon.com/gp/bestsellers/electronics/6459737011/ref=sr_bs_1_6459737011_1",
    },
    carousel: {
      id: "loom-desktop-bottom-slot_sptw-deals-blended-na-desktop-T4",
      title: "Today's deals",
      total_items: 5,
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    image: "https://m.media-amazon.com/images/I/81kRxFTpd1L._AC_UL320_.jpg",
    is_carousel: true,
    link: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_search_thematic_btf_aps_sr_pg1_2?ie=UTF8&bwType=search&bwAsin=B08Z265BJH&url=%2FInsignia-50-inch-Class-Smart-Fire%2Fdp%2FB08Z265BJH%2Fref%3Dsxbs_pa_sp_search_thematic_btf_sspa%3Fcontent-id%3Damzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%253Aamzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%26cv_ct_cx%3Dtv%26keywords%3Dtv%26pd_rd_i%3DB08Z265BJH%26pd_rd_r%3D05dd59e4-8cae-48ac-b8c0-f38bdeb61b44%26pd_rd_w%3DvlVGw%26pd_rd_wg%3D8M4SW%26pf_rd_p%3Ddfb5d868-54e5-4c02-b76d-0b517246ef24%26pf_rd_r%3DK94SPT2DX03FY395YTR8%26qid%3D1659571144%26sr%3D1-2-97bafd84-a21b-4eac-aafb-f1e805a45134-spons%26psc%3D1&qualifier=1659571144&id=1920463823263837&widgetName=sp_search_thematic_btf",
    position: 18,
    price: {
      currency: "USD",
      is_primary: true,
      name: "$239.99",
      raw: "$239.99",
      symbol: "$",
      value: 239.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "$239.99",
        raw: "$239.99",
        symbol: "$",
        value: 239.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "$239.99",
        raw: "$399.99",
        symbol: "$",
        value: 399.99,
      },
    ],
    rating: 4.6,
    ratings_total: 1210,
    title:
      "Insignia 50-inch Class F30 Series LED 4K UHD Smart Fire TV (NS-50F301NA22, 2021 Model)",
  },
  {
    asin: "B09SBL34C4",
    carousel: {
      id: "loom-desktop-bottom-slot_sptw-deals-blended-na-desktop-T4",
      title: "Today's deals",
      total_items: 5,
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    image: "https://m.media-amazon.com/images/I/81CxhXJtoNL._AC_UL320_.jpg",
    is_carousel: true,
    is_prime: true,
    link: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_search_thematic_btf_aps_sr_pg1_3?ie=UTF8&bwType=search&bwAsin=B09SBL34C4&url=%2FSAMSUNG-65-Inch-Quantum-Tracking-QN65QN800BFXZA%2Fdp%2FB09SBL34C4%2Fref%3Dsxbs_pa_sp_search_thematic_btf_sspa%3Fcontent-id%3Damzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%253Aamzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%26cv_ct_cx%3Dtv%26keywords%3Dtv%26pd_rd_i%3DB09SBL34C4%26pd_rd_r%3D05dd59e4-8cae-48ac-b8c0-f38bdeb61b44%26pd_rd_w%3DvlVGw%26pd_rd_wg%3D8M4SW%26pf_rd_p%3Ddfb5d868-54e5-4c02-b76d-0b517246ef24%26pf_rd_r%3DK94SPT2DX03FY395YTR8%26qid%3D1659571144%26sr%3D1-3-97bafd84-a21b-4eac-aafb-f1e805a45134-spons%26psc%3D1&qualifier=1659571144&id=1920463823263837&widgetName=sp_search_thematic_btf",
    position: 19,
    price: {
      currency: "USD",
      is_primary: true,
      name: "$2,997.99",
      raw: "$2,997.99",
      symbol: "$",
      value: 2997.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "$2,997.99",
        raw: "$2,997.99",
        symbol: "$",
        value: 2997.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "$2,997.99",
        raw: "$3,497.99",
        symbol: "$",
        value: 3497.99,
      },
    ],
    rating: 5,
    ratings_total: 11,
    title:
      "SAMSUNG 65-Inch Class Neo QLED 8K QN800B Series Mini LED Quantum HDR 32x, Dolby Atmos, Object Tracking Sound+, Ultra Viewing Angle, Smart TV with Alexa Built-In (QN65QN800BFXZA, 2022 Model)",
  },
  {
    asin: "B08X7K3H7K",
    carousel: {
      id: "loom-desktop-bottom-slot_sptw-deals-blended-na-desktop-T4",
      title: "Today's deals",
      total_items: 5,
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    image: "https://m.media-amazon.com/images/I/81DnMWhQ2gL._AC_UL320_.jpg",
    is_carousel: true,
    link: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_search_thematic_btf_aps_sr_pg1_4?ie=UTF8&bwType=search&bwAsin=B08X7K3H7K&url=%2FInsignia-43-inch-Class-Smart-Fire%2Fdp%2FB08X7K3H7K%2Fref%3Dsxbs_pa_sp_search_thematic_btf_sspa%3Fcontent-id%3Damzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%253Aamzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%26cv_ct_cx%3Dtv%26keywords%3Dtv%26pd_rd_i%3DB08X7K3H7K%26pd_rd_r%3D05dd59e4-8cae-48ac-b8c0-f38bdeb61b44%26pd_rd_w%3DvlVGw%26pd_rd_wg%3D8M4SW%26pf_rd_p%3Ddfb5d868-54e5-4c02-b76d-0b517246ef24%26pf_rd_r%3DK94SPT2DX03FY395YTR8%26qid%3D1659571144%26sr%3D1-4-97bafd84-a21b-4eac-aafb-f1e805a45134-spons%26psc%3D1&qualifier=1659571144&id=1920463823263837&widgetName=sp_search_thematic_btf",
    position: 20,
    price: {
      currency: "USD",
      is_primary: true,
      name: "$189.99",
      raw: "$189.99",
      symbol: "$",
      value: 189.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "$189.99",
        raw: "$189.99",
        symbol: "$",
        value: 189.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "$189.99",
        raw: "$299.99",
        symbol: "$",
        value: 299.99,
      },
    ],
    rating: 4.6,
    ratings_total: 4128,
    title:
      "Insignia 43-inch Class F30 Series LED 4K UHD Smart Fire TV (NS-43F301NA22, 2021 Model)",
  },
  {
    asin: "B08X7JSCHQ",
    carousel: {
      id: "loom-desktop-bottom-slot_sptw-deals-blended-na-desktop-T4",
      title: "Today's deals",
      total_items: 5,
    },
    categories: [
      {
        id: "aps",
        name: "All Departments",
      },
    ],
    deal: {
      badge_text: "Limited time deal",
      link: "https://www.amazon.com/gp/goldbox/",
    },
    image: "https://m.media-amazon.com/images/I/61qXHwJeGVS._AC_UL320_.jpg",
    is_carousel: true,
    link: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_search_thematic_btf_aps_sr_pg1_5?ie=UTF8&bwType=search&bwAsin=B08X7JSCHQ&url=%2FAll-New-Insignia-NS-32F201NA22-32-inch-Released%2Fdp%2FB08X7JSCHQ%2Fref%3Dsxbs_pa_sp_search_thematic_btf_sspa%3Fcontent-id%3Damzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%253Aamzn1.sym.dfb5d868-54e5-4c02-b76d-0b517246ef24%26cv_ct_cx%3Dtv%26keywords%3Dtv%26pd_rd_i%3DB08X7JSCHQ%26pd_rd_r%3D05dd59e4-8cae-48ac-b8c0-f38bdeb61b44%26pd_rd_w%3DvlVGw%26pd_rd_wg%3D8M4SW%26pf_rd_p%3Ddfb5d868-54e5-4c02-b76d-0b517246ef24%26pf_rd_r%3DK94SPT2DX03FY395YTR8%26qid%3D1659571144%26sr%3D1-5-97bafd84-a21b-4eac-aafb-f1e805a45134-spons%26psc%3D1&qualifier=1659571144&id=1920463823263837&widgetName=sp_search_thematic_btf",
    position: 21,
    price: {
      currency: "USD",
      is_primary: true,
      name: "$119.99",
      raw: "$119.99",
      symbol: "$",
      value: 119.99,
    },
    prices: [
      {
        currency: "USD",
        is_primary: true,
        name: "$119.99",
        raw: "$119.99",
        symbol: "$",
        value: 119.99,
      },
      {
        currency: "USD",
        is_rrp: true,
        name: "$119.99",
        raw: "$179.99",
        symbol: "$",
        value: 179.99,
      },
    ],
    rating: 4.5,
    ratings_total: 2280,
    title:
      "Insignia 32-inch Class F20 Series Smart HD 720p Fire TV (NS-32F201NA22, 2021 Model)",
  },
]

export default SampleData;